"""Init database structure

Revision ID: 15a9da2a1a04
Revises: 
Create Date: 2026-05-28 09:30:32.050298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15a9da2a1a04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='finding_source_pkey'),
    sa.UniqueConstraint('code', name='finding_source_code_key')
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('composition_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('phonogram_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name='label_pkey'),
    sa.UniqueConstraint('name', name='label_name_key')
    )
    op.create_index('idx_label_name', 'label', ['name'], unique=True)
    op.create_table('mv_catalog_flat',
    sa.Column('track_id', sa.BigInteger(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('upc', sa.Text(), nullable=True),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('track_name', sa.Text(), nullable=True),
    sa.Column('genre_name', sa.Text(), nullable=True),
    sa.Column('album_name', sa.Text(), nullable=True),
    sa.Column('track_number', sa.Text(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('track_artist_name', sa.Text(), nullable=True),
    sa.Column('composer', sa.Text(), nullable=True),
    sa.Column('lyricist', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('explicit', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('right_id', sa.Text(), nullable=True),
    sa.Column('author_right_int', sa.Text(), nullable=True),
    sa.Column('author_right_mob', sa.Text(), nullable=True),
    sa.Column('author_right_pub', sa.Text(), nullable=True),
    sa.Column('ar_label_treaty_number', sa.Text(), nullable=True),
    sa.Column('related_right_id_int', sa.Text(), nullable=True),
    sa.Column('related_right_id_mob', sa.Text(), nullable=True),
    sa.Column('related_right_id_pub', sa.Text(), nullable=True),
    sa.Column('rr_label_treaty_number', sa.Text(), nullable=True)
    )
    op.create_index('idx_mv_catalog_flat_label_id', 'mv_catalog_flat', ['label_id'], unique=False)
    op.create_index('idx_mv_catalog_flat_track_id', 'mv_catalog_flat', ['track_id'], unique=True)
    op.create_table('mv_track_extended',
    sa.Column('track_id', sa.BigInteger(), nullable=True),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('track_name', sa.Text(), nullable=True),
    sa.Column('label_own_code', sa.Text(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('track_artist_name', sa.Text(), nullable=True),
    sa.Column('composer', sa.Text(), nullable=True),
    sa.Column('lyricist', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('upc', sa.Text(), nullable=True),
    sa.Column('genre_name', sa.Text(), nullable=True),
    sa.Column('album_name', sa.Text(), nullable=True),
    sa.Column('track_number', sa.Text(), nullable=True),
    sa.Column('explicit', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True)
    )
    op.create_index('idx__mv_track_extended__track_id', 'mv_track_extended', ['track_id'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', postgresql.CITEXT(), nullable=False),
    sa.Column('tokens', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('norm_key_full', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_pkey'),
    sa.UniqueConstraint('full_name', name='person_full_name_key')
    )
    op.create_index('idx_person_full_name_norm', 'person', ['full_name'], unique=False)
    op.create_index('idx_person_norm_key', 'person', ['norm_key_full'], unique=False)
    op.create_index('idx_person_norm_key_full', 'person', ['norm_key_full'], unique=False)
    op.create_index('idx_person_tokens_gin', 'person', ['tokens'], unique=False, postgresql_using='gin')
    op.create_index('idx_person_unique_norm_key', 'person', ['norm_key_full'], unique=True)
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='region_pkey'),
    sa.UniqueConstraint('code', name='region_code_key')
    )
    op.create_table('right_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='right_category_pkey'),
    sa.UniqueConstraint('name', name='right_category_name_key')
    )
    op.create_table('right_usage_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='right_usage_type_pkey'),
    sa.UniqueConstraint('code', name='right_usage_type_code_key')
    )
    op.create_table('staging_catalog',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('upc', sa.Text(), nullable=True),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('track_name', sa.Text(), nullable=True),
    sa.Column('genre_name', sa.Text(), nullable=True),
    sa.Column('album_name', sa.Text(), nullable=True),
    sa.Column('album_single', sa.Text(), nullable=True),
    sa.Column('track_number', sa.Text(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('track_artist_name', sa.Text(), nullable=True),
    sa.Column('composer', sa.Text(), nullable=True),
    sa.Column('lyricist', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('explicit', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('total_author_right', sa.Text(), nullable=True),
    sa.Column('right_id', sa.Text(), nullable=True),
    sa.Column('author_right_1', sa.Text(), nullable=True),
    sa.Column('ar_label_treaty_number_1', sa.Text(), nullable=True),
    sa.Column('author_right_2', sa.Text(), nullable=True),
    sa.Column('ar_label_treaty_number_2', sa.Text(), nullable=True),
    sa.Column('author_right_3', sa.Text(), nullable=True),
    sa.Column('ar_label_treaty_number_3', sa.Text(), nullable=True),
    sa.Column('total_related_right', sa.Text(), nullable=True),
    sa.Column('related_right_id_1', sa.Text(), nullable=True),
    sa.Column('rr_label_treaty_number_1', sa.Text(), nullable=True),
    sa.Column('related_right_id_2', sa.Text(), nullable=True),
    sa.Column('rr_label_treaty_number_2', sa.Text(), nullable=True),
    sa.Column('related_right_id_3', sa.Text(), nullable=True),
    sa.Column('rr_label_treaty_number_3', sa.Text(), nullable=True),
    sa.Column('types_of_rights', sa.Text(), nullable=True),
    sa.Column('countries', sa.Text(), nullable=True),
    sa.Column('create_date', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Text(), nullable=True),
    sa.Column('sales_start_date', sa.Text(), nullable=True),
    sa.Column('has_ringtone', sa.Text(), nullable=True),
    sa.Column('ringtone_upc', sa.Text(), nullable=True),
    sa.Column('ringtone_isrc', sa.Text(), nullable=True),
    sa.Column('has_vclip', sa.Text(), nullable=True),
    sa.Column('vclip_isrc', sa.Text(), nullable=True),
    sa.Column('video_upc', sa.Text(), nullable=True),
    sa.Column('has_lyrics', sa.Text(), nullable=True),
    sa.Column('has_ttml', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Text(), nullable=True),
    sa.Column('termination_date', sa.Text(), nullable=True),
    sa.Column('active_inactive', sa.Text(), nullable=True),
    sa.Column('resource_reference', sa.Text(), nullable=True),
    sa.Column('track_id', sa.Text(), nullable=True),
    sa.Column('track_song_id', sa.Text(), nullable=True),
    sa.Column('upload_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('track_name_norm_key', sa.Text(), nullable=True),
    sa.Column('track_name_tokens', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name='staging_catalog_pkey')
    )
    op.create_table('staging_catalog_v2',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('track_id', sa.Text(), nullable=True),
    sa.Column('track_song_id', sa.Text(), nullable=True),
    sa.Column('upc', sa.Text(), nullable=True),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('track_name', sa.Text(), nullable=True),
    sa.Column('genre_name', sa.Text(), nullable=True),
    sa.Column('album_name', sa.Text(), nullable=True),
    sa.Column('album_single', sa.Text(), nullable=True),
    sa.Column('track_number', sa.Text(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('track_artist_name', sa.Text(), nullable=True),
    sa.Column('composer', sa.Text(), nullable=True),
    sa.Column('lyricist', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('explicit', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('right_id', sa.Text(), nullable=True),
    sa.Column('author_right_int', sa.Text(), nullable=True),
    sa.Column('author_right_mob', sa.Text(), nullable=True),
    sa.Column('author_right_pub', sa.Text(), nullable=True),
    sa.Column('ar_label_treaty_number', sa.Text(), nullable=True),
    sa.Column('related_right_id_int', sa.Text(), nullable=True),
    sa.Column('related_right_id_mob', sa.Text(), nullable=True),
    sa.Column('related_right_id_pub', sa.Text(), nullable=True),
    sa.Column('rr_label_treaty_number', sa.Text(), nullable=True),
    sa.Column('types_of_rights', sa.Text(), nullable=True),
    sa.Column('countries', sa.Text(), nullable=True),
    sa.Column('create_date', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Text(), nullable=True),
    sa.Column('sales_start_date', sa.Text(), nullable=True),
    sa.Column('has_ringtone', sa.Text(), nullable=True),
    sa.Column('ringtone_upc', sa.Text(), nullable=True),
    sa.Column('ringtone_isrc', sa.Text(), nullable=True),
    sa.Column('has_vclip', sa.Text(), nullable=True),
    sa.Column('vclip_isrc', sa.Text(), nullable=True),
    sa.Column('video_upc', sa.Text(), nullable=True),
    sa.Column('has_lyrics', sa.Text(), nullable=True),
    sa.Column('has_ttml', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Text(), nullable=True),
    sa.Column('termination_date', sa.Text(), nullable=True),
    sa.Column('active_inactive', sa.Text(), nullable=True),
    sa.Column('resource_reference', sa.Text(), nullable=True),
    sa.Column('upload_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('track_name_norm_key', sa.Text(), nullable=True),
    sa.Column('track_name_tokens', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name='staging_catalog_v2_pkey')
    )
    op.create_index('idx_staging_v2_isrc', 'staging_catalog_v2', ['isrc'], unique=False)
    op.create_index('idx_staging_v2_upc', 'staging_catalog_v2', ['upc'], unique=False)
    op.create_index('idx_staging_v2_upload_id', 'staging_catalog_v2', ['upload_id'], unique=False)
    op.create_table('staging_person',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', postgresql.CITEXT(), nullable=False),
    sa.Column('staging_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name_norm_key', sa.Text(), nullable=True),
    sa.Column('tokens', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('upload_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='staging_person_pkey')
    )
    op.create_index('idx_staging_person_staging_id', 'staging_person', ['staging_id'], unique=False)
    op.create_index('idx_staging_person_upload_id', 'staging_person', ['upload_id'], unique=False)
    op.create_table('staging_report',
    sa.Column('row_number', sa.Text(), nullable=True),
    sa.Column('label_own_code', sa.Text(), nullable=True),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('track_name', sa.Text(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('composer', sa.Text(), nullable=True),
    sa.Column('lyricist', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('author_share_pct', sa.Text(), nullable=True),
    sa.Column('related_share_pct', sa.Text(), nullable=True),
    sa.Column('play_count', sa.Text(), nullable=True),
    sa.Column('payout_amount', sa.Text(), nullable=True),
    sa.Column('price_per_play', sa.Text(), nullable=True),
    sa.Column('service_name', sa.Text(), nullable=True),
    sa.Column('upload_id', sa.Text(), nullable=True)
    )
    op.create_index('idx_staging_report_upload_id', 'staging_report', ['upload_id'], unique=False)
    op.create_table('staging_report_agg',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('label_own_code', sa.Text(), nullable=True),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('track_name', sa.Text(), nullable=True),
    sa.Column('track_name_norm_key', sa.Text(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('service_name', sa.Text(), nullable=True),
    sa.Column('play_count', sa.BigInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('payout_amount', sa.Numeric(precision=20, scale=8), server_default=sa.text('0.0'), nullable=True),
    sa.Column('price_per_play', sa.Numeric(precision=20, scale=8), server_default=sa.text('0.0'), nullable=True),
    sa.Column('isfound', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('artist_name_tokens', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('artist_name_norm_key_full', sa.Text(), nullable=True),
    sa.Column('authors_tokens', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('authors_norm_key_full', sa.Text(), nullable=True),
    sa.Column('upload_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='staging_report_agg_pkey')
    )
    op.create_index('idx_staging_report_agg_upload_id', 'staging_report_agg', ['upload_id'], unique=False)
    op.create_index('idx_staging_report_artist_key', 'staging_report_agg', ['artist_name_norm_key_full'], unique=False)
    op.create_index('idx_staging_report_auth_key', 'staging_report_agg', ['authors_norm_key_full'], unique=False)
    op.create_index('idx_staging_report_isfound', 'staging_report_agg', ['isfound'], unique=False, postgresql_where='(isfound = false)')
    op.create_index('idx_staging_report_track_key', 'staging_report_agg', ['track_name_norm_key'], unique=False)
    op.create_table('staging_report_ids',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('staging_id', sa.BigInteger(), nullable=False),
    sa.Column('track_id', sa.BigInteger(), nullable=False),
    sa.Column('finding_source', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='staging_report_ids_pkey')
    )
    op.create_index('idx_staging_report_ids_staging_id', 'staging_report_ids', ['staging_id'], unique=False)
    op.create_index('idx_staging_report_ids_track_id', 'staging_report_ids', ['track_id'], unique=False)
    op.create_index('idx_staging_report_ids_upload_id', 'staging_report_ids', ['upload_id'], unique=False)
    op.create_table('track',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('isrc', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('explicit', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('resource_reference', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('label_own_code', sa.String(length=50), nullable=True),
    sa.Column('title_tokens', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('title_norm_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='track_pkey')
    )
    op.create_index('idx_track_contribution_lookup', 'track', ['isrc', 'label_own_code', 'title'], unique=False)
    op.create_index('idx_track_isrc', 'track', ['isrc'], unique=False)
    op.create_index('idx_track_isrc_label_own_code', 'track', ['isrc', 'label_own_code'], unique=False)
    op.create_index('idx_track_label_own_code', 'track', ['label_own_code'], unique=False)
    op.create_index('idx_track_title', 'track', ['title'], unique=False)
    op.create_index('idx_track_title_norm_btree', 'track', ['title_norm_key'], unique=False)
    op.create_index('idx_track_title_norm_trgm', 'track', ['title_norm_key'], unique=False, postgresql_ops={'title_norm_key': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_table('track_full_info',
    sa.Column('id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('isrc', sa.String(length=20), nullable=True),
    sa.Column('label_own_code', sa.String(length=50), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('composer', sa.Text(), nullable=True),
    sa.Column('lyricist', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True)
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', postgresql.CITEXT(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('full_name', name='user_full_name_key'),
    sa.UniqueConstraint('login', name='user_login_key')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('right_usage_type_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['right_usage_type_id'], ['right_usage_type.id'], name='partners_right_usage_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='partners_pkey'),
    sa.UniqueConstraint('organization_name', 'service_name', name='partners_organization_name_service_name_key')
    )
    op.create_table('release',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('upc', sa.String(length=20), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'Active'::character varying"), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name='release_label_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='release_pkey'),
    sa.UniqueConstraint('upc', name='release_upc_key')
    )
    op.create_index('idx_release_upc', 'release', ['upc'], unique=False)
    op.create_table('right_holder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name='right_holder_label_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='right_holder_pkey'),
    sa.UniqueConstraint('name', name='right_holder_name_key')
    )
    op.create_index('idx_right_holder_name', 'right_holder', ['name'], unique=True)
    op.create_table('track_contribution',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('track_id', sa.BigInteger(), nullable=True),
    sa.Column('person_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='track_contribution_person_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='track_contribution_track_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='track_contribution_pkey'),
    sa.UniqueConstraint('track_id', 'person_id', 'role', name='track_contribution_unique_key')
    )
    op.create_index('idx_tc_track_role_person', 'track_contribution', ['track_id', 'role', 'person_id'], unique=False)
    op.create_index('idx_track_contribution_person_id', 'track_contribution', ['person_id'], unique=False)
    op.create_index('idx_track_contribution_track_id', 'track_contribution', ['track_id'], unique=False)
    op.create_table('track_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name='track_label_label_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='track_label_track_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='track_label_pkey'),
    sa.UniqueConstraint('track_id', 'label_id', name='track_label_track_id_label_id_key'),
    sa.UniqueConstraint('track_id', 'label_id', name='track_label_unique_idx')
    )
    op.create_table('contract',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('treaty_number', sa.String(length=255), nullable=False),
    sa.Column('right_holder_id', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['right_holder_id'], ['right_holder.id'], name='contract_right_holder_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contract_pkey'),
    sa.UniqueConstraint('treaty_number', name='contract_treaty_number_key')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('right_category_id', sa.Integer(), nullable=False),
    sa.Column('right_usage_type_id', sa.Integer(), nullable=False),
    sa.Column('report_month', sa.Integer(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('payout_amount', sa.Numeric(precision=20, scale=4), server_default=sa.text('0.0'), nullable=True),
    sa.Column('price_per_play', sa.Numeric(precision=20, scale=6), server_default=sa.text('0.0'), nullable=True),
    sa.Column('upload_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name='report_partner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_category_id'], ['right_category.id'], name='report_right_category_id_fkey'),
    sa.ForeignKeyConstraint(['right_usage_type_id'], ['right_usage_type.id'], name='report_right_usage_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='report_pkey')
    )
    op.create_table('track_release',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], name='track_release_release_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='track_release_track_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'release_id', name='track_release_pkey')
    )
    op.create_index('idx_track_release_release_id', 'track_release', ['release_id'], unique=False)
    op.create_index('idx_track_release_track_id', 'track_release', ['track_id'], unique=False)
    op.create_table('report_track_rights_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('right_category_id', sa.Integer(), nullable=False),
    sa.Column('right_usage_type_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('right_holder_id', sa.Integer(), nullable=False),
    sa.Column('share_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('staging_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name='fk_report', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_category_id'], ['right_category.id'], name='fk_right_category'),
    sa.ForeignKeyConstraint(['right_holder_id'], ['right_holder.id'], name='fk_right_holder'),
    sa.ForeignKeyConstraint(['right_usage_type_id'], ['right_usage_type.id'], name='fk_right_usage_type'),
    sa.ForeignKeyConstraint(['staging_id'], ['staging_report_agg.id'], name='fk_staging_report', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='fk_track'),
    sa.PrimaryKeyConstraint('id', name='report_track_rights_cache_pkey')
    )
    op.create_index('idx_report_track_rights_report_id', 'report_track_rights_cache', ['report_id'], unique=False)
    op.create_index('idx_report_track_rights_track_id', 'report_track_rights_cache', ['track_id'], unique=False)
    op.create_table('track_right',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('track_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('right_holder_id', sa.Integer(), nullable=True),
    sa.Column('right_category_id', sa.Integer(), nullable=True),
    sa.Column('share_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('right_usage_type_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=30), nullable=True),
    sa.CheckConstraint('share_percentage >= 0::numeric AND share_percentage <= 100::numeric', name='track_right_share_percentage_check'),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name='track_right_contract_id_fkey'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name='track_right_region_id_fkey'),
    sa.ForeignKeyConstraint(['right_category_id'], ['right_category.id'], name='track_right_right_category_id_fkey'),
    sa.ForeignKeyConstraint(['right_holder_id'], ['right_holder.id'], name='track_right_right_holder_id_fkey'),
    sa.ForeignKeyConstraint(['right_usage_type_id'], ['right_usage_type.id'], name='track_right_right_usage_type_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='track_right_track_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='track_right_pkey')
    )
    op.create_index('idx_track_right_right_holder_id', 'track_right', ['right_holder_id'], unique=False)
    op.create_index('idx_track_right_track_id', 'track_right', ['track_id'], unique=False)
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index('idx_track_right_track_id', table_name='track_right')
    op.drop_index('idx_track_right_right_holder_id', table_name='track_right')
    op.drop_table('track_right')
    op.drop_index('idx_report_track_rights_track_id', table_name='report_track_rights_cache')
    op.drop_index('idx_report_track_rights_report_id', table_name='report_track_rights_cache')
    op.drop_table('report_track_rights_cache')
    op.drop_index('idx_track_release_track_id', table_name='track_release')
    op.drop_index('idx_track_release_release_id', table_name='track_release')
    op.drop_table('track_release')
    op.drop_table('report')
    op.drop_table('contract')
    op.drop_table('track_label')
    op.drop_index('idx_track_contribution_track_id', table_name='track_contribution')
    op.drop_index('idx_track_contribution_person_id', table_name='track_contribution')
    op.drop_index('idx_tc_track_role_person', table_name='track_contribution')
    op.drop_table('track_contribution')
    op.drop_index('idx_right_holder_name', table_name='right_holder')
    op.drop_table('right_holder')
    op.drop_index('idx_release_upc', table_name='release')
    op.drop_table('release')
    op.drop_table('partners')
    op.drop_table('user')
    op.drop_table('track_full_info')
    op.drop_index('idx_track_title_norm_trgm', table_name='track', postgresql_ops={'title_norm_key': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_track_title_norm_btree', table_name='track')
    op.drop_index('idx_track_title', table_name='track')
    op.drop_index('idx_track_label_own_code', table_name='track')
    op.drop_index('idx_track_isrc_label_own_code', table_name='track')
    op.drop_index('idx_track_isrc', table_name='track')
    op.drop_index('idx_track_contribution_lookup', table_name='track')
    op.drop_table('track')
    op.drop_index('idx_staging_report_ids_upload_id', table_name='staging_report_ids')
    op.drop_index('idx_staging_report_ids_track_id', table_name='staging_report_ids')
    op.drop_index('idx_staging_report_ids_staging_id', table_name='staging_report_ids')
    op.drop_table('staging_report_ids')
    op.drop_index('idx_staging_report_track_key', table_name='staging_report_agg')
    op.drop_index('idx_staging_report_isfound', table_name='staging_report_agg', postgresql_where='(isfound = false)')
    op.drop_index('idx_staging_report_auth_key', table_name='staging_report_agg')
    op.drop_index('idx_staging_report_artist_key', table_name='staging_report_agg')
    op.drop_index('idx_staging_report_agg_upload_id', table_name='staging_report_agg')
    op.drop_table('staging_report_agg')
    op.drop_index('idx_staging_report_upload_id', table_name='staging_report')
    op.drop_table('staging_report')
    op.drop_index('idx_staging_person_upload_id', table_name='staging_person')
    op.drop_index('idx_staging_person_staging_id', table_name='staging_person')
    op.drop_table('staging_person')
    op.drop_index('idx_staging_v2_upload_id', table_name='staging_catalog_v2')
    op.drop_index('idx_staging_v2_upc', table_name='staging_catalog_v2')
    op.drop_index('idx_staging_v2_isrc', table_name='staging_catalog_v2')
    op.drop_table('staging_catalog_v2')
    op.drop_table('staging_catalog')
    op.drop_table('right_usage_type')
    op.drop_table('right_category')
    op.drop_table('region')
    op.drop_index('idx_person_unique_norm_key', table_name='person')
    op.drop_index('idx_person_tokens_gin', table_name='person', postgresql_using='gin')
    op.drop_index('idx_person_norm_key_full', table_name='person')
    op.drop_index('idx_person_norm_key', table_name='person')
    op.drop_index('idx_person_full_name_norm', table_name='person')
    op.drop_table('person')
    op.drop_index('idx__mv_track_extended__track_id', table_name='mv_track_extended')
    op.drop_table('mv_track_extended')
    op.drop_index('idx_mv_catalog_flat_track_id', table_name='mv_catalog_flat')
    op.drop_index('idx_mv_catalog_flat_label_id', table_name='mv_catalog_flat')
    op.drop_table('mv_catalog_flat')
    op.drop_index('idx_label_name', table_name='label')
    op.drop_table('label')
    op.drop_table('finding_source')
    # ### end Alembic commands ###
