"""add_period_and_payout_fields

Revision ID: b378978c23eb
Revises: 15a9da2a1a04
Create Date: 2026-07-08 14:53:17.049251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b378978c23eb'
down_revision: Union[str, Sequence[str], None] = '15a9da2a1a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('partners_right_usage_type_id_fkey', 'partners', 'right_usage_type', ['right_usage_type_id'], ['id'])
    op.add_column('staging_report', sa.Column('period', sa.Text(), nullable=True))
    op.add_column('staging_report', sa.Column('payout_amount_author', sa.Text(), nullable=True))
    op.add_column('staging_report', sa.Column('payout_amount_related', sa.Text(), nullable=True))
    op.add_column('staging_report_agg', sa.Column('period', sa.String(length=100), nullable=True))
    op.add_column('staging_report_agg', sa.Column('payout_amount_author', sa.Numeric(precision=20, scale=8), server_default=sa.text('0.0'), nullable=True))
    op.add_column('staging_report_agg', sa.Column('payout_amount_related', sa.Numeric(precision=20, scale=8), server_default=sa.text('0.0'), nullable=True))
    op.create_unique_constraint('track_label_unique_idx', 'track_label', ['track_id', 'label_id'])
    op.create_unique_constraint('user_full_name_key', 'user', ['full_name'])

    op.create_table(
        'report_track_rights_distribution',
        sa.Column('id', sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column('report_id', sa.BigInteger(), nullable=False),
        sa.Column('staging_id', sa.BigInteger(), nullable=False),
        sa.Column('track_id', sa.BigInteger(), nullable=False),
        sa.Column('right_holder_id', sa.BigInteger(), nullable=False),
        sa.Column('right_category_id', sa.Integer(), nullable=False),
        sa.Column('right_usage_type_id', sa.Integer(), nullable=False),
        sa.Column('original_share_percentage', sa.Numeric(10, 4), nullable=False),
        sa.Column('calculated_share_percentage', sa.Numeric(10, 4), nullable=False),
        sa.Column('final_payout_amount', sa.Numeric(15, 6), nullable=False),
        sa.Column('is_normalized', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True)
    )
   
    op.create_index('idx_rights_dist_report', 'report_track_rights_distribution', ['report_id'])
    op.create_index('idx_rtrd_report_staging', 'report_track_rights_distribution', ['report_id', 'staging_id'])


    op.execute("""
    CREATE OR REPLACE FUNCTION clean_and_split(text_field TEXT) 
    RETURNS TEXT[] AS $$
    BEGIN
        RETURN string_to_array(
            -- 1. regexp_replace заменяет все разделители на один (;)
            -- 2. btrim убирает все указанные символы (пробелы, слэши, запятые) по краям
            btrim(
                regexp_replace(text_field, '[/,:;]+', ';', 'g'), 
                ' ,/;:'
            ), 
            ';'
        );
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION public.clean_and_split_person_names(text_field text) RETURNS text[]
            LANGUAGE plpgsql
            AS $$
        BEGIN
            -- NULL или пустая строка → пустой массив
            IF text_field IS NULL OR trim(text_field) = '' THEN
                RETURN ARRAY[]::text[];
            END IF;

            RETURN (
                SELECT array_agg(trim(elem))
                FROM (
                    SELECT unnest(regexp_split_to_array(
                        text_field,
                        -- разделители: ; | , : / (только если / окружён пробелами)
                        '\\s*[;|,:]\\s*|\\s+/\\s+'
                    )) AS elem
                ) sub
                WHERE trim(elem) != ''
            );
        END;
        $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""


    op.drop_index('idx_rtrd_report_staging', table_name='report_track_rights_distribution')
    op.drop_index('idx_rights_dist_report', table_name='report_track_rights_distribution')
    op.drop_table('report_track_rights_distribution')


    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_full_name_key', 'user', type_='unique')
    op.drop_constraint('track_label_unique_idx', 'track_label', type_='unique')
    op.drop_column('staging_report_agg', 'payout_amount_related')
    op.drop_column('staging_report_agg', 'payout_amount_author')
    op.drop_column('staging_report_agg', 'period')
    op.drop_column('staging_report', 'payout_amount_related')
    op.drop_column('staging_report', 'payout_amount_author')
    op.drop_column('staging_report', 'period')
    op.drop_constraint('partners_right_usage_type_id_fkey', 'partners', type_='foreignkey')
    # ### end Alembic commands ###
