TRUNCATE TABLE track_right RESTART IDENTITY CASCADE;
TRUNCATE TABLE track_contribution RESTART IDENTITY CASCADE;
TRUNCATE TABLE track_release RESTART IDENTITY CASCADE;
TRUNCATE TABLE track RESTART IDENTITY CASCADE;
TRUNCATE TABLE release RESTART IDENTITY CASCADE;
TRUNCATE TABLE contract RESTART IDENTITY CASCADE;
TRUNCATE TABLE right_holder RESTART IDENTITY CASCADE;
TRUNCATE TABLE person RESTART IDENTITY CASCADE;

TRUNCATE TABLE staging_catalog RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging_report RESTART IDENTITY CASCADE;
TRUNCATE TABLE report RESTART IDENTITY CASCADE;



TRUNCATE TABLE label RESTART IDENTITY CASCADE;
TRUNCATE TABLE right_usage_type RESTART IDENTITY CASCADE;
TRUNCATE TABLE right_category RESTART IDENTITY CASCADE;



TRUNCATE TABLE person RESTART IDENTITY CASCADE;
TRUNCATE TABLE label RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging_catalog RESTART IDENTITY CASCADE;


-- 1. Удаляем схему со всем содержимым (таблицы, представления, функции)
DROP SCHEMA public CASCADE;

-- 2. Создаем новую чистую схему
CREATE SCHEMA public;

-- 3. Восстанавливаем права доступа (важно для PostgreSQL)
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";